### ISSUE TITLE
Configure Front50 Storage Options

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#106]
This will probably look something like

```yaml
persistentStorage:
  accountName: my-[aws/google]-account
  bucketName: # either user specified, or randomly generated by halyard
  rootFolder: spinnaker
```
