### ISSUE TITLE
Configure Spinnaker Access/Security

### ISSUE THREAD

**Issue by lwander** [spinnaker/halyard#108]
The gist of the features is to make [this](http://www.spinnaker.io/docs/securing-spinnaker) easier. Since I don't have much experience securing Spinnaker: @ttomsu, could you list a few common sticking points during this config process?

**Comment by lwander** [comment]
So my thoughts on preliminary config are

```yaml
security:
  apiDomain:    # fully qualified domain name, `null` when none exists
  apiAddress:   # defaults to localhost
  uiDomain:     # fully qualified domain name, `null` when none exists
  uiAddress:    # defaults to localhost
  ssl:
    enabled:
    serverKeyPath:
    caKeyPath:
    keystorePassword:   # one password for all keys due to tomcat limitation
    keystoreAlias:
    keystorePath:
  authn:
    enabled:    # when false, assume/create ssh tunnels
    oauth2:
      # all gate - spring.oauth settings go here (client, resource userInfoMapping)
    saml2:
    x509:
  authz:
    # gafw config
```
