### ISSUE TITLE
Kubeconfig pointing to certificate files is not supported

### ISSUE THREAD

**Issue by OrfeasZ** [spinnaker/halyard#594]
This seems to be a two part issue, caused by both halyard and the fabric8 kubernetes client (I'll open an issue on their tracker too and link it here). 

When the specified kubeconfig points to certificate/key files instead of embedding their data directly (as seen below) hal fails to configure the provider with the error `Unable to authenticate with your Kubernetes cluster. Try using kubectl to verify your credentials.`.

Sample (incomplete) kubeconfig:
```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /path/to/ca.pem
    server: https://some-k8s-server
  name: some-cluster
users:
- name: admin
  user:
    client-certificate: /path/to/client.pem
    client-key: /path/to/client-key.pem
```

After further inspection it seems that this issue is caused because of the following reasons:

1. If any of the certs are pointed to using relative paths the fabric8 client fails to properly look them up.
2. Fabric8 for some reason expects the certs to be DER encoded (instead of PEM).

It's fairly easy to work around these two issues but then that causes even more issues:

1. After deployment, the kubeconfig file that's uploaded to the cluster points to an nonexistent absolute path, since hal doesn't also push/mount the certificate files through secrets.
2. Because of the above, Spinnaker cannot properly detect the Kubernetes environment it's running in and defaults to a misconfigured AWS-backed environment.

The obvious workaround for all these issues is embedding the certificate data in the kubeconfig file directly, but it would be nice to see a configuration like this supported.
