### ISSUE TITLE
Adding container shaping to Halyard deployed replicasets

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/halyard#683]
Discussed this with @lwander and we decided that this will be our first approach:

```
deploymentEnvironment:
    size: SMALL
    customSizing:
      clouddriver:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
         memory: "128Mi"
         cpu: "500m"
      echo:
        request:
          memory: "64Mi"
          cpu: "250m"
        limits:
         memory: "128Mi"
         cpu: "500m"
    type: Distributed
    accountName: my-k8s-cluster
    consul:
      enabled: false
    vault:
      enabled: false
    location: my-spinnaker-namespace
```

Any service that doesn't have a customSizing section associated with it will receive no sizing at the moment, and at some point if size: SMALL or size: MEDIUM have presets it would fall back to those.

Open to discussion, but Target will be working on this approach soon.
